pipeline:

  hello:
#   host: "oji.0j0.jp"
#   username: "9zilla"
#   port: 22
#   image: appleboy/drone-ssh
#   secrets: [ ssh_key ]
    image: alpine:3.6
#   script:
#     - echo hello
    commands:
      - echo "Hello"
    when:
      branch: master
