setup:
	apt-get install libncurses5 libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev pkg-config

install:
	pip install git+https://github.com/nobiki/gaccho_${PACKAGE}.git

update:
	pip install -U git+https://github.com/nobiki/gaccho_${PACKAGE}.git

remove:
	pip uninstall gaccho-${PACKAGE}
